services:
  frontend:
    platform: "linux/amd64"
    build:
      context: "."
      dockerfile: ./Dockerfile
      platforms:
        - "linux/arm64"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 6000:5000
    networks: 
      - my-networks
  db:
    image: mysql:8.0.27
    links:
      - frontend
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=estoque
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
volumes:
  db_data:
networks:
  my-networks:
    driver: bridge  