  services:
    api:
      container_name: api-estoque
      platform: "linux/amd64"
      build:
        context: "."
        dockerfile: ./Dockerfile
      environment:
        HOST: db #usar essas variaveis no app.py
        USER: root
        PASSWORD: root
        DATABASE: estoque
        PORT: 3306
      links:
        - db
      depends_on:
        - db
      restart: on-failure
      ports:
        - 6000:5000

    db:
      container_name: db-estoque
      platform: "linux/amd64"
      image: mysql:8.0.27
      command: mysqld --init-file=/docker-entrypoint-initdb.d/init.sql --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - '3306:3306'
      volumes:
        - './db/data:/var/lib/mysql'
        - './db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql'